// 由住宿名單自動產生（365 人）。日後名單異動改這裡再重跑 seed。
export type SeedStudent = {
  region?: string | null; // 地區（上層分類），例：'明新'、'萬能'、'啟英'；一般宿舍生可省略
  building: string; // 棟別代號，例：'A'、'B'、'C'…
  className: string;
  studentNo: string | null;
  name: string;
  gender: string | null;
  room: string | null;
  floor: number | null;
  company?: string | null; // 建教合作班的工讀公司，一般宿舍生沒有可省略
  active?: boolean | null; // false = 目前不住宿舍，不列入回報/統計；省略或 null 視為 true
  note: string | null;
};

export const seedStudents: SeedStudent[] = [
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資三甲A",
    "studentNo": "381113",
    "name": "周日瓊",
    "gender": "女",
    "room": "401",
    "floor": null,
    "company": null,
    "active": true,
    "note": "華語文未過"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資三甲A",
    "studentNo": "381106",
    "name": "李家映",
    "gender": "女",
    "room": "401",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑餐二甲A",
    "studentNo": "483110",
    "name": "武氏英書",
    "gender": "女",
    "room": "401",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑餐二甲A",
    "studentNo": "483115",
    "name": "殷芝玲",
    "gender": "女",
    "room": "401",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581121",
    "name": "徐玉芳",
    "gender": "女",
    "room": "402",
    "floor": null,
    "company": "碩陽",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581118",
    "name": "范美芳",
    "gender": "女",
    "room": "402",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581134",
    "name": "葉氏瓊如",
    "gender": "女",
    "room": "402",
    "floor": null,
    "company": "碩陽",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581125",
    "name": "陳玉慶玄",
    "gender": "女",
    "room": "402",
    "floor": null,
    "company": "碩陽",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582117",
    "name": "張清清",
    "gender": "女",
    "room": "404",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582115",
    "name": "徐佳萱",
    "gender": "女",
    "room": "404",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582109",
    "name": "李嘉英",
    "gender": "女",
    "room": "404",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582102",
    "name": "王楠",
    "gender": "女",
    "room": "404",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582116",
    "name": "張英如",
    "gender": "女",
    "room": "405",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "382126",
    "name": "楊美麗",
    "gender": "女",
    "room": "405",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582127",
    "name": "蘇如瓊",
    "gender": "女",
    "room": "405",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582110",
    "name": "阮氏清賢",
    "gender": "女",
    "room": "405",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582125",
    "name": "盧日貞",
    "gender": "女",
    "room": "406",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582111",
    "name": "阮玉仙",
    "gender": "女",
    "room": "406",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582121",
    "name": "黃許寶兒",
    "gender": "女",
    "room": "406",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582122",
    "name": "黃錦秀",
    "gender": "女",
    "room": "406",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581138",
    "name": "劉氏翠雲",
    "gender": "女",
    "room": "407",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581101",
    "name": "王玉英",
    "gender": "女",
    "room": "407",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581102",
    "name": "王玉雲",
    "gender": "女",
    "room": "407",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581122",
    "name": "馬家惠",
    "gender": "女",
    "room": "407",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581120",
    "name": "唐美緣",
    "gender": "女",
    "room": "408",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581115",
    "name": "祁氏如玉",
    "gender": "女",
    "room": "408",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581123",
    "name": "許美玲",
    "gender": "女",
    "room": "408",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581124",
    "name": "陳玉天金",
    "gender": "女",
    "room": "408",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582107",
    "name": "李宗煥",
    "gender": "女",
    "room": "501",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582106",
    "name": "李宗雯",
    "gender": "女",
    "room": "501",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": null,
    "name": "賈靜玲",
    "gender": "女",
    "room": "501",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582104",
    "name": "朱李娟",
    "gender": "女",
    "room": "502",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581141",
    "name": "潘金英",
    "gender": "女",
    "room": "502",
    "floor": null,
    "company": "台林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582124",
    "name": "農玉娟",
    "gender": "女",
    "room": "502",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582113",
    "name": "周和燕",
    "gender": "女",
    "room": "503",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582119",
    "name": "覃李梅",
    "gender": "女",
    "room": "503",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582112",
    "name": "阮陳玉草",
    "gender": "女",
    "room": "503",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582120",
    "name": "馮霞霓",
    "gender": "女",
    "room": "503",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582101",
    "name": "孔芳英",
    "gender": "女",
    "room": "504",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582114",
    "name": "范氏金銀",
    "gender": "女",
    "room": "504",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582126",
    "name": "蘇又郁",
    "gender": "女",
    "room": "504",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時一甲A",
    "studentNo": "582118",
    "name": "陳清竹",
    "gender": "女",
    "room": "504",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581136",
    "name": "廖樹鳳",
    "gender": "女",
    "room": "505",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581113",
    "name": "林千佩",
    "gender": "女",
    "room": "505",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581114",
    "name": "林爵金",
    "gender": "女",
    "room": "505",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581131",
    "name": "黃小燕",
    "gender": "女",
    "room": "505",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581111",
    "name": "冼昇秀玲",
    "gender": "女",
    "room": "506",
    "floor": null,
    "company": "台林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581143",
    "name": "盧鴛媚",
    "gender": "女",
    "room": "506",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581117",
    "name": "范氏玉鳳",
    "gender": "女",
    "room": "506",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資一甲A",
    "studentNo": "581130",
    "name": "馮錦雲",
    "gender": "女",
    "room": "506",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482120",
    "name": "梅竹玲",
    "gender": "女",
    "room": "507",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482115",
    "name": "武氏錦緣",
    "gender": "女",
    "room": "507",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482104",
    "name": "王亦美",
    "gender": "女",
    "room": "507",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482117",
    "name": "范美麗",
    "gender": "女",
    "room": "507",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482129",
    "name": "楊曉曼",
    "gender": "女",
    "room": "508",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482131",
    "name": "趙湘琴",
    "gender": "女",
    "room": "508",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482121",
    "name": "陳亮茹",
    "gender": "女",
    "room": "508",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482126",
    "name": "黃茵茵",
    "gender": "女",
    "room": "508",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482108",
    "name": "朱星怡",
    "gender": "女",
    "room": "509",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482128",
    "name": "楊再再",
    "gender": "女",
    "room": "509",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482107",
    "name": "王雪",
    "gender": "女",
    "room": "509",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482123",
    "name": "陳曉嵐",
    "gender": "女",
    "room": "509",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑資三甲A",
    "studentNo": "381101",
    "name": "江日英",
    "gender": "女",
    "room": "510",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482102",
    "name": "寸心柔",
    "gender": "女",
    "room": "607",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482111",
    "name": "李心梅",
    "gender": "女",
    "room": "607",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482113",
    "name": "李美鳳",
    "gender": "女",
    "room": "607",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英女",
    "className": "僑時二甲A",
    "studentNo": "482130",
    "name": "楊麗麗",
    "gender": "女",
    "room": "607",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑時一甲A",
    "studentNo": "582103",
    "name": "朱永賢",
    "gender": "男",
    "room": "201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑時一甲A",
    "studentNo": "582105",
    "name": "朱飛龍",
    "gender": "男",
    "room": "201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑時一甲A",
    "studentNo": "582108",
    "name": "李家雄",
    "gender": "男",
    "room": "201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581112",
    "name": "周業成",
    "gender": "男",
    "room": "202",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581107",
    "name": "阮青達",
    "gender": "男",
    "room": "202",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581109",
    "name": "阮黃寶南",
    "gender": "男",
    "room": "202",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581128",
    "name": "陸基",
    "gender": "男",
    "room": "202",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581139",
    "name": "劉功文",
    "gender": "男",
    "room": "203",
    "floor": null,
    "company": "模帝科",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581105",
    "name": "李泰峰",
    "gender": "男",
    "room": "203",
    "floor": null,
    "company": "模帝科",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581116",
    "name": "胡曰登",
    "gender": "男",
    "room": "203",
    "floor": null,
    "company": "模帝科",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581106",
    "name": "阮明日",
    "gender": "男",
    "room": "203",
    "floor": null,
    "company": "模帝科",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481114",
    "name": "孫起權",
    "gender": "男",
    "room": "204",
    "floor": null,
    "company": "佳鼎",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481105",
    "name": "李曉鵬",
    "gender": "男",
    "room": "204",
    "floor": null,
    "company": "佳鼎",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑時二甲A",
    "studentNo": "482124",
    "name": "馮伯盛",
    "gender": "男",
    "room": "204",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481119",
    "name": "黃明輝",
    "gender": "男",
    "room": "204",
    "floor": null,
    "company": "佳鼎",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581129",
    "name": "湯大杰",
    "gender": "男",
    "room": "205",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581119",
    "name": "范登科",
    "gender": "男",
    "room": "205",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581144",
    "name": "謝明光",
    "gender": "男",
    "room": "205",
    "floor": null,
    "company": "泰詠",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581127",
    "name": "陳潘丹長",
    "gender": "男",
    "room": "205",
    "floor": null,
    "company": "泰詠",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581140",
    "name": "劉玉龍",
    "gender": "男",
    "room": "206",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581104",
    "name": "吳李福",
    "gender": "男",
    "room": "206",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581133",
    "name": "溫家倫",
    "gender": "男",
    "room": "206",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581132",
    "name": "黃亞康",
    "gender": "男",
    "room": "206",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581108",
    "name": "阮春壽",
    "gender": "男",
    "room": "207",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581110",
    "name": "阮維光",
    "gender": "男",
    "room": "207",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581126",
    "name": "陳明德",
    "gender": "男",
    "room": "207",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581142",
    "name": "黎光天",
    "gender": "男",
    "room": "207",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581145",
    "name": "嚴富慶",
    "gender": "男",
    "room": "208",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581103",
    "name": "朱金發",
    "gender": "男",
    "room": "208",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581135",
    "name": "葉成金",
    "gender": "男",
    "room": "208",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資一甲A",
    "studentNo": "581137",
    "name": "趙齡輝",
    "gender": "男",
    "room": "208",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381102",
    "name": "呂日飛",
    "gender": "男",
    "room": "301",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381108",
    "name": "李鍠龍",
    "gender": "男",
    "room": "301",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381131",
    "name": "馮黃飛",
    "gender": "男",
    "room": "301",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481127",
    "name": "劉家健",
    "gender": "男",
    "room": "302",
    "floor": null,
    "company": "佳鼎",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑時二甲A",
    "studentNo": "482112",
    "name": "李星文",
    "gender": "男",
    "room": "302",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381115",
    "name": "林家豪",
    "gender": "男",
    "room": "302",
    "floor": null,
    "company": "模帝科",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑時二甲A",
    "studentNo": "482116",
    "name": "武明山",
    "gender": "男",
    "room": "302",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑餐二甲A",
    "studentNo": "483103",
    "name": "何深偉",
    "gender": "男",
    "room": "303",
    "floor": null,
    "company": null,
    "active": true,
    "note": "華語文未過"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481122",
    "name": "楊宗傑",
    "gender": "男",
    "room": "303",
    "floor": null,
    "company": null,
    "active": true,
    "note": "華語文未過"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481101",
    "name": "甘秀成",
    "gender": "男",
    "room": "303",
    "floor": null,
    "company": null,
    "active": true,
    "note": "華語文未過"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481106",
    "name": "阮廷魁",
    "gender": "男",
    "room": "303",
    "floor": null,
    "company": null,
    "active": true,
    "note": "欲休學"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381123",
    "name": "梁平富",
    "gender": "男",
    "room": "304",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381128",
    "name": "程興發",
    "gender": "男",
    "room": "304",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381139",
    "name": "趙福天",
    "gender": "男",
    "room": "304",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381135",
    "name": "黃達源",
    "gender": "男",
    "room": "304",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381103",
    "name": "李世榮",
    "gender": "男",
    "room": "305",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381105",
    "name": "李明棋",
    "gender": "男",
    "room": "305",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑餐二甲A",
    "studentNo": "483117",
    "name": "梅黎英進",
    "gender": "男",
    "room": "305",
    "floor": null,
    "company": "MOMO",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資三甲A",
    "studentNo": "381144",
    "name": "謝積詠",
    "gender": "男",
    "room": "305",
    "floor": null,
    "company": null,
    "active": true,
    "note": "退廠"
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481104",
    "name": "何義才",
    "gender": "男",
    "room": "306",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481124",
    "name": "楊高福",
    "gender": "男",
    "room": "306",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481129",
    "name": "鄧國大",
    "gender": "男",
    "room": "306",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "啟英",
    "building": "啟英男",
    "className": "僑資二甲A",
    "studentNo": "481120",
    "name": "黃家寶",
    "gender": "男",
    "room": "306",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "劉玉龍",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "湯大杰",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "溫家倫",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "范登科",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "吳李福",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "阮春壽",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "黃亞康",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "黎光天",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "葉成金",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "趙齡輝",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "阮維光",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "陳明德",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481133",
    "name": "賴羅發",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481130",
    "name": "鄧福輝",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481108",
    "name": "阮晉達",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481134",
    "name": "龐才祿",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481109",
    "name": "阮清平",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481112",
    "name": "韋國才",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481113",
    "name": "韋國晉",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481111",
    "name": "韋海龍",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481104",
    "name": "何義才",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381119",
    "name": "唐德龍",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481117",
    "name": "曾李權",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381146",
    "name": "李金明",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381147",
    "name": "張浩",
    "gender": "男",
    "room": "1106",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381107",
    "name": "李華源",
    "gender": "男",
    "room": "1106",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381118",
    "name": "范德信",
    "gender": "男",
    "room": "1106",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381126",
    "name": "曾明達",
    "gender": "男",
    "room": "1114",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381109",
    "name": "沈月生",
    "gender": "男",
    "room": "1114",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381145",
    "name": "蘇光明",
    "gender": "男",
    "room": "1114",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381121",
    "name": "徐從傑",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381120",
    "name": "徐昌新",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381116",
    "name": "林寶貴",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "王玉英",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "王玉雲",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "范美芳",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "馬家惠",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "劉氏翠雲",
    "gender": "女",
    "room": "1419",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "盧鴛媚",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "范氏玉鳳",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "陳玉天金",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "馮錦雲",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "唐美緣",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "祁氏如玉",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資一甲A",
    "studentNo": null,
    "name": "許美玲",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481123",
    "name": "楊珮玉",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481118",
    "name": "黃氏雪如",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481131",
    "name": "黎氏芳薇",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481132",
    "name": "黎氏英書",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481115",
    "name": "張金萍",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481110",
    "name": "段玉珊",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481103",
    "name": "江明雪",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481128",
    "name": "盤嬌娥",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481116",
    "name": "傅美容",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481102",
    "name": "石潮鴻",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481135",
    "name": "蘇美鳳",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資三甲A",
    "studentNo": "381125",
    "name": "陳官蓮",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": null,
    "name": "張月鳳",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481125",
    "name": "楊瓊英",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新A",
    "className": "僑資二甲A",
    "studentNo": "481126",
    "name": "楊瓊華",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": false,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": null,
    "name": "唐國利",
    "gender": "男",
    "room": "1001",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481218",
    "name": "張亞心",
    "gender": "男",
    "room": "1001",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "鄭家福",
    "gender": "男",
    "room": "1001",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "陳英福",
    "gender": "男",
    "room": "1001",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481213",
    "name": "林首望",
    "gender": "男",
    "room": "1014",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481214",
    "name": "武必貴",
    "gender": "男",
    "room": "1014",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481215",
    "name": "洪智海",
    "gender": "男",
    "room": "1014",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481211",
    "name": "阮成義",
    "gender": "男",
    "room": "1014",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "唐國榮",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "廖貴熙",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "鄭達成",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "阮潘進才",
    "gender": "男",
    "room": "1023",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "冼天棋",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "張發龍",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "阮武嘉龍",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "黃德富",
    "gender": "男",
    "room": "1026",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "何侶俊傑",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "吳文達",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "周為貴",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "阮福盛",
    "gender": "男",
    "room": "1028",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481216",
    "name": "唐國發",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481224",
    "name": "甯玉清松",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481230",
    "name": "葉開進",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481221",
    "name": "陳清豐富",
    "gender": "男",
    "room": "1032",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481223",
    "name": "曾駱俊",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481209",
    "name": "李偉君",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481208",
    "name": "李定傑",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481202",
    "name": "氏豪",
    "gender": "男",
    "room": "1038",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481207",
    "name": "李其添",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381227",
    "name": "黃光雄",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381228",
    "name": "黃至君",
    "gender": "男",
    "room": "1101",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381240",
    "name": "盤廣光",
    "gender": "男",
    "room": "1106",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381241",
    "name": "蔡權玲",
    "gender": "男",
    "room": "1106",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381226",
    "name": "黃企宏",
    "gender": "男",
    "room": "1106",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381235",
    "name": "廖日天",
    "gender": "男",
    "room": "1114",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381223",
    "name": "曾李福",
    "gender": "男",
    "room": "1114",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381242",
    "name": "鄧雲祥",
    "gender": "男",
    "room": "1114",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381220",
    "name": "張發金",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381214",
    "name": "武黃輝寶",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381245",
    "name": "蘇世平",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381209",
    "name": "阮英其",
    "gender": "男",
    "room": "1115",
    "floor": 1,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "嚴彩琳",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "姚兆芳",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "張德蓮",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "趙氏清玄",
    "gender": "女",
    "room": "1417",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "吳家佳",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "鍾文恩",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "陳嘉欣",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "黎水香",
    "gender": "女",
    "room": "1420",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481217",
    "name": "唐詠如",
    "gender": "女",
    "room": "1449",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "沈氏春",
    "gender": "女",
    "room": "1449",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "潘竹玲",
    "gender": "女",
    "room": "1449",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "阮雪梅",
    "gender": "女",
    "room": "1449",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "吳家琪",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "宋垂莊",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "譚斯慇",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資一甲B",
    "studentNo": null,
    "name": "陳金玉",
    "gender": "女",
    "room": "1460",
    "floor": 4,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481203",
    "name": "何玉茶媚",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481204",
    "name": "何美慧",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481210",
    "name": "李寶千",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481220",
    "name": "陳明孝",
    "gender": "女",
    "room": "1510",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481201",
    "name": "文氏翠雲",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481233",
    "name": "盤玉玲",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481234",
    "name": "蔡恩桂",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481232",
    "name": "趙氏雪雲",
    "gender": "女",
    "room": "1511",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381204",
    "name": "余玉杏",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381247",
    "name": "李林美",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381215",
    "name": "胡氏芳容",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381243",
    "name": "鄭金英",
    "gender": "女",
    "room": "1516",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資三甲B",
    "studentNo": "381246",
    "name": "李佳薇",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481205",
    "name": "李氏金莊",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481206",
    "name": "李氏金雲",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481227",
    "name": "黃鴛芳",
    "gender": "女",
    "room": "1530",
    "floor": 5,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "明新",
    "building": "明新B",
    "className": "僑資二甲B",
    "studentNo": "481212",
    "name": "阮黃家寶",
    "gender": "男",
    "room": null,
    "floor": null,
    "company": null,
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382113",
    "name": "張游修",
    "gender": "女",
    "room": "1201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382121",
    "name": "黃青竹",
    "gender": "女",
    "room": "1201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382131",
    "name": "黎氏青蓮",
    "gender": "女",
    "room": "1201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382132",
    "name": "龐日鴛",
    "gender": "女",
    "room": "1201",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381138",
    "name": "廖凱貞",
    "gender": "女",
    "room": "1202",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381143",
    "name": "盧日珍",
    "gender": "女",
    "room": "1202",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "482231",
    "name": "鄧美玲",
    "gender": "女",
    "room": "1202",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381125",
    "name": "陳官蓮",
    "gender": "女",
    "room": "1202",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382103",
    "name": "吳金玲",
    "gender": "女",
    "room": "1203",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382102",
    "name": "朱美燕",
    "gender": "女",
    "room": "1203",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382115",
    "name": "許南英",
    "gender": "女",
    "room": "1203",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382120",
    "name": "麥氏蘭",
    "gender": "女",
    "room": "1203",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481116",
    "name": "傅美容",
    "gender": "女",
    "room": "1204",
    "floor": null,
    "company": "泰詠",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481110",
    "name": "段玉珊",
    "gender": "女",
    "room": "1204",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481102",
    "name": "石潮鴻",
    "gender": "女",
    "room": "1204",
    "floor": null,
    "company": "泰詠",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481135",
    "name": "蘇美鳳",
    "gender": "女",
    "room": "1204",
    "floor": null,
    "company": "泰詠",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382111",
    "name": "徐氏祥微",
    "gender": "女",
    "room": "1205",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481103",
    "name": "江明雪",
    "gender": "女",
    "room": "1205",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382118",
    "name": "陸家玉",
    "gender": "女",
    "room": "1205",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481118",
    "name": "黃氏雪如",
    "gender": "女",
    "room": "1205",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381122",
    "name": "徐鈺鳳",
    "gender": "女",
    "room": "1207",
    "floor": null,
    "company": "碩陽",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381137",
    "name": "楊懷竹玉",
    "gender": "女",
    "room": "1207",
    "floor": null,
    "company": "碩陽",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381132",
    "name": "黃可兒",
    "gender": "女",
    "room": "1207",
    "floor": null,
    "company": "碩陽",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382134",
    "name": "李可琪",
    "gender": "女",
    "room": "1208",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382108",
    "name": "李慧珊",
    "gender": "女",
    "room": "1208",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382128",
    "name": "楊舒琪",
    "gender": "女",
    "room": "1208",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382130",
    "name": "裴夏微",
    "gender": "女",
    "room": "1208",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382109",
    "name": "阮氏艷馥",
    "gender": "女",
    "room": "1209",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381129",
    "name": "馮宜嫻",
    "gender": "女",
    "room": "1209",
    "floor": null,
    "company": "尖點",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382125",
    "name": "黃黎芳鴛",
    "gender": "女",
    "room": "1209",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382114",
    "name": "梅氏映原",
    "gender": "女",
    "room": "1210",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483113",
    "name": "韋氏金鳳",
    "gender": "女",
    "room": "1211",
    "floor": null,
    "company": "漢來",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483119",
    "name": "黃可欣",
    "gender": "女",
    "room": "1211",
    "floor": null,
    "company": "漢來",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483125",
    "name": "黎慶玲",
    "gender": "女",
    "room": "1211",
    "floor": null,
    "company": "王品",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483124",
    "name": "黎氏紅絨",
    "gender": "女",
    "room": "1211",
    "floor": null,
    "company": "王品",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時二甲A",
    "studentNo": "482132",
    "name": "劉愛菲",
    "gender": "女",
    "room": "1212",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時二甲A",
    "studentNo": "482127",
    "name": "楊氏翠銀",
    "gender": "女",
    "room": "1212",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382126",
    "name": "楊美麗",
    "gender": "女",
    "room": "1212",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時二甲A",
    "studentNo": "482122",
    "name": "陳雪鳳",
    "gender": "女",
    "room": "1212",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481136",
    "name": "張月鳳",
    "gender": "女",
    "room": "1215",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481115",
    "name": "張金萍",
    "gender": "女",
    "room": "1215",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481128",
    "name": "盤嬌娥",
    "gender": "女",
    "room": "1215",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481131",
    "name": "黎氏芳薇",
    "gender": "女",
    "room": "1215",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483112",
    "name": "范黎芳貞",
    "gender": "女",
    "room": "1216",
    "floor": null,
    "company": "三合院",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483122",
    "name": "農氏瓊簪",
    "gender": "女",
    "room": "1217",
    "floor": null,
    "company": "爭鮮",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483121",
    "name": "黃霞薇",
    "gender": "女",
    "room": "1217",
    "floor": null,
    "company": "爭鮮",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "482109",
    "name": "何玉婷",
    "gender": "女",
    "room": "1219",
    "floor": null,
    "company": "三商",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483129",
    "name": "嚴志玲",
    "gender": "女",
    "room": "1219",
    "floor": null,
    "company": "王品",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483116",
    "name": "張氏寶如",
    "gender": "女",
    "room": "1219",
    "floor": null,
    "company": "青青(桃)",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑餐二甲A",
    "studentNo": "483101",
    "name": "王菊芬",
    "gender": "女",
    "room": "1219",
    "floor": null,
    "company": "青青(桃)",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "382216",
    "name": "周家如",
    "gender": "女",
    "room": "1220",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381127",
    "name": "曾金玉",
    "gender": "女",
    "room": "1220",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381124",
    "name": "梁美雪華",
    "gender": "女",
    "room": "1220",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資三甲A",
    "studentNo": "381140",
    "name": "潘黃如",
    "gender": "女",
    "room": "1220",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時二甲A",
    "studentNo": "482101",
    "name": "丁氏月瑜",
    "gender": "女",
    "room": "1221",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382129",
    "name": "廖氏美玲",
    "gender": "女",
    "room": "1221",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382122",
    "name": "黃雅鴛",
    "gender": "女",
    "room": "1221",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑時三甲A",
    "studentNo": "382133",
    "name": "龐李娟",
    "gender": "女",
    "room": "1221",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481123",
    "name": "楊珮玉",
    "gender": "女",
    "room": "1222",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481125",
    "name": "楊瓊英",
    "gender": "女",
    "room": "1222",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481126",
    "name": "楊瓊華",
    "gender": "女",
    "room": "1222",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能女",
    "className": "僑資二甲A",
    "studentNo": "481132",
    "name": "黎氏英書",
    "gender": "女",
    "room": "1222",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483102",
    "name": "何啟源",
    "gender": "男",
    "room": "1301",
    "floor": null,
    "company": "青青(北)",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483108",
    "name": "來西五",
    "gender": "男",
    "room": "1301",
    "floor": null,
    "company": "青青(北)",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381118",
    "name": "范德信",
    "gender": "男",
    "room": "1301",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": null,
    "name": "轉生5",
    "gender": "男",
    "room": "1301",
    "floor": null,
    "company": "青青(北)",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481117",
    "name": "曾李權",
    "gender": "男",
    "room": "1302",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481112",
    "name": "韋國才",
    "gender": "男",
    "room": "1302",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481113",
    "name": "韋國晉",
    "gender": "男",
    "room": "1302",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481111",
    "name": "韋海龍",
    "gender": "男",
    "room": "1302",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": null,
    "name": "轉生2",
    "gender": "男",
    "room": "1303",
    "floor": null,
    "company": "MOMO",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": null,
    "name": "轉生3",
    "gender": "男",
    "room": "1303",
    "floor": null,
    "company": "MOMO",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": null,
    "name": "轉生4",
    "gender": "男",
    "room": "1303",
    "floor": null,
    "company": "MOMO",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483111",
    "name": "邱猛芳",
    "gender": "男",
    "room": "1304",
    "floor": null,
    "company": "瓦城",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483104",
    "name": "何源海",
    "gender": "男",
    "room": "1305",
    "floor": null,
    "company": "瓦城",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483128",
    "name": "徐有東",
    "gender": "男",
    "room": "1305",
    "floor": null,
    "company": "瓦城",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483130",
    "name": "鄧阮英科",
    "gender": "男",
    "room": "1305",
    "floor": null,
    "company": "瓦城",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483118",
    "name": "馮昌香",
    "gender": "男",
    "room": "1305",
    "floor": null,
    "company": "瓦城",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483109",
    "name": "官好雋",
    "gender": "男",
    "room": "1306",
    "floor": null,
    "company": "三商",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483120",
    "name": "黃立權",
    "gender": "男",
    "room": "1306",
    "floor": null,
    "company": "王品",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483107",
    "name": "阮寶南",
    "gender": "男",
    "room": "1307",
    "floor": null,
    "company": "點點心",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483106",
    "name": "阮成龍",
    "gender": "男",
    "room": "1307",
    "floor": null,
    "company": "點點心",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483114",
    "name": "唐國家",
    "gender": "男",
    "room": "1308",
    "floor": null,
    "company": "瓦城",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": null,
    "name": "轉生1",
    "gender": "男",
    "room": "1308",
    "floor": null,
    "company": "三商",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑時二甲A",
    "studentNo": "482103",
    "name": "文進寶",
    "gender": "男",
    "room": "1309",
    "floor": null,
    "company": "名留",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381119",
    "name": "唐德龍",
    "gender": "男",
    "room": "1310",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑時三甲A",
    "studentNo": "382123",
    "name": "黃達芳",
    "gender": "男",
    "room": "1310",
    "floor": null,
    "company": "曼都",
    "active": true,
    "note": "實習住校"
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481107",
    "name": "阮家貴",
    "gender": "男",
    "room": "1311",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481108",
    "name": "阮晉達",
    "gender": "男",
    "room": "1311",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481109",
    "name": "阮清平",
    "gender": "男",
    "room": "1311",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381116",
    "name": "林寶貴",
    "gender": "男",
    "room": "1312",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381109",
    "name": "沈月生",
    "gender": "男",
    "room": "1312",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483123",
    "name": "鄧達秀",
    "gender": "男",
    "room": "1312",
    "floor": null,
    "company": "漢來",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑餐二甲A",
    "studentNo": "483105",
    "name": "阮文趙寶",
    "gender": "男",
    "room": "1312",
    "floor": null,
    "company": "漢來",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381126",
    "name": "曾明達",
    "gender": "男",
    "room": "1314",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481133",
    "name": "賴羅發",
    "gender": "男",
    "room": "1314",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481130",
    "name": "鄧福輝",
    "gender": "男",
    "room": "1314",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資二甲A",
    "studentNo": "481134",
    "name": "龐才祿",
    "gender": "男",
    "room": "1314",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑時三甲A",
    "studentNo": "382101",
    "name": "左文方",
    "gender": "男",
    "room": "1315",
    "floor": null,
    "company": "小林",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381147",
    "name": "張浩",
    "gender": "男",
    "room": "1315",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381104",
    "name": "李明皇",
    "gender": "男",
    "room": "1315",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381146",
    "name": "李金明",
    "gender": "男",
    "room": "1315",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381117",
    "name": "施光俊英",
    "gender": "男",
    "room": "1316",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381112",
    "name": "阮源成",
    "gender": "男",
    "room": "1316",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381133",
    "name": "黃永佩",
    "gender": "男",
    "room": "1316",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381142",
    "name": "黎光明",
    "gender": "男",
    "room": "1316",
    "floor": null,
    "company": "欣興",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381121",
    "name": "徐從傑",
    "gender": "男",
    "room": "1317",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381120",
    "name": "徐昌新",
    "gender": "男",
    "room": "1317",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381107",
    "name": "李華源",
    "gender": "男",
    "room": "1317",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  },
  {
    "region": "萬能",
    "building": "萬能男",
    "className": "僑資三甲A",
    "studentNo": "381145",
    "name": "蘇光明",
    "gender": "男",
    "room": "1317",
    "floor": null,
    "company": "鴻佰",
    "active": true,
    "note": null
  }
];
